version: '3.8'

services:
  datastore:
    image: miko-datastore
    build: datastore
    environment:
      POSTGRES_PASSWORD: mikopass
#    volumes :
#      - miko-data:/var/lib/postgresql/data
    ports:
      - 8001:5432
  miko:
    image: miko-app
    build: miko
    working_dir: /miko
    depends_on:
      - datastore
    environment:
      MIKO_DB_CONNSTRING: postgresql://postgres:mikopass@datastore:5432
    volumes:
      - ./miko:/miko
    ports:
      - 5000:5000

volumes:
  miko-data: