version: '3.8'

services:
  miko_mq:
    image: rabbitmq:3.8.7
    ports:
      - 5672:5672
  datastore:
    image: miko-datastore
    build: datastore
    environment:
      POSTGRES_PASSWORD: mikopass
    volumes :
      - miko-data:/var/lib/postgresql/data
    ports:
      - 8001:5432
  miko_dal:
    image: miko-dal
    build: miko_dal
    working_dir: /miko_dal
    depends_on:
      - datastore
      - miko_mq
    environment:
      MIKO_DB_CONNSTRING: postgresql://postgres:mikopass@datastore:5432
    volumes:
      - ./miko_dal:/miko_dal
  miko:
    image: miko-app
    build: miko
    working_dir: /miko
    depends_on:
      - miko_dal
      - miko_mq
    environment:
      MIKO_MQ_HOST: miko_mq
    volumes:
      - ./miko:/miko
    ports:
      - 5000:5000

volumes:
  miko-data: